import { StyleSheet } from 'react-native';

import { Spacing, type ThemeColors } from '@/constants/theme';

export function makeBarcodeStyles(colors: ThemeColors, insets: { top: number; bottom: number }) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    overlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      alignItems: 'center',
      justifyContent: 'center',
    },
    camera: {
      flex: 1,
    },
    reticle: {
      width: 220,
      height: 220,
      borderWidth: 3,
      borderColor: colors.accent,
      borderRadius: 16,
      backgroundColor: 'transparent',
    },
    hintRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.two,
      marginTop: Spacing.three,
      backgroundColor: 'rgba(0,0,0,0.55)',
      paddingVertical: Spacing.two,
      paddingHorizontal: Spacing.three,
      borderRadius: 8,
    },
    scanHint: {
      fontSize: 14,
      lineHeight: 20,
      color: '#FFFFFF',
      textAlign: 'center',
    },
    invalidText: {
      marginTop: Spacing.two,
      fontSize: 14,
      color: '#FFD5D2',
      textAlign: 'center',
      backgroundColor: 'rgba(0,0,0,0.55)',
      paddingVertical: Spacing.two,
      paddingHorizontal: Spacing.three,
      borderRadius: 8,
      overflow: 'hidden',
    },
    invalidActions: {
      position: 'absolute',
      left: Spacing.four,
      right: Spacing.four,
      bottom: insets.bottom + 24,
    },
    continuousBar: {
      position: 'absolute',
      top: insets.top + 12,
      left: Spacing.three,
      right: Spacing.three,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.7)',
      borderRadius: 10,
      paddingVertical: Spacing.two,
      paddingHorizontal: Spacing.three,
    },
    continuousText: {
      flex: 1,
      fontSize: 13,
      color: '#FFFFFF',
    },
    continuousStop: {
      paddingVertical: Spacing.two,
      paddingHorizontal: Spacing.three,
      borderRadius: 8,
      backgroundColor: colors.danger,
    },
    continuousStopText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.onDanger,
    },
    startContinuousButton: {
      position: 'absolute',
      left: Spacing.four,
      right: Spacing.four,
      bottom: insets.bottom + 80,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.65)',
      paddingVertical: Spacing.two,
      borderRadius: 10,
    },
    startContinuousText: {
      fontSize: 15,
      fontWeight: '600',
      color: '#FFFFFF',
    },
    pendingCard: {
      marginHorizontal: Spacing.four,
      backgroundColor: colors.backgroundElement,
      borderRadius: 14,
      padding: Spacing.four,
      gap: Spacing.two,
      alignItems: 'center',
    },
    sheetClose: {
      alignSelf: 'flex-end',
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: -Spacing.three,
      marginRight: -Spacing.three,
    },
    backdrop: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    sheetScroll: {
      flexGrow: 1,
      justifyContent: 'center',
    },
    pendingTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
    },
    pendingMagazine: {
      fontSize: 17,
      fontWeight: '600',
      color: colors.accentTextOnLight,
      textAlign: 'center',
    },
    pendingMessage: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
    },
    pendingCancel: {
      minHeight: 44,
      justifyContent: 'center',
      paddingVertical: Spacing.two,
      paddingHorizontal: Spacing.three,
    },
    pendingCancelText: {
      fontSize: 16,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    primaryButton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.accent,
      minHeight: 48,
      paddingVertical: Spacing.two,
      paddingHorizontal: Spacing.three,
      borderRadius: 12,
      alignSelf: 'stretch',
    },
    primaryButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.accentText,
      textAlign: 'center',
    },
    buttonPressed: {
      opacity: 0.8,
    },
    backButton: {
      position: 'absolute',
      top: insets.top + 12,
      left: Spacing.three,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(0,0,0,0.55)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    torchButton: {
      position: 'absolute',
      top: insets.top + 12,
      right: Spacing.three,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(0,0,0,0.55)',
      alignItems: 'center',
      justifyContent: 'center',
    },
  });
}

export type BarcodeStyles = ReturnType<typeof makeBarcodeStyles>;
